version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20

  - package-ecosystem: 'github-actions'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
