name: Build & Test

on:
  pull_request:
    branches: [master, next, "*.x", beta, alpha]
  push:
    branches: [master, next, "*.x", beta, alpha]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-dependencies-cache:
    if: ${{ github.event_name	== 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

  test:
    if: ${{ github.event_name	!= 'push' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 18.x
            script: lint
          - node: 18.x
            script: build
          - node: 16.x
            script: test
          - node: 18.x
            script: test
          - node: 20.x
            script: test
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: ${{ format('Run {0}', matrix.script) }}
        run: npm run ${{ matrix.script }}