name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - '*.x'

env:
  HUSKY: 0

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm clean-install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npx semantic-release

      - name: Sync alpha and latest dist-tags
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Wait for the dist-tags to be updated
          sleep 60

          # Sync the alpha and latest dist-tags
          .scripts/sync-alpha-and-latest.sh
